### PR TITLE
fix: proper comparison for string

### LINKED ISSUE #9: Typo in privilege string 'partner'
https://github.com/sourcetoad/tizen-build-action/blob/fb6685eff3762ee1bb172ee738e87fa4432a8ccd/build.sh#L17
Should be `partner`

### PR DESCRIPTION
**Pull request by iBotPeaches**
```
/home/runner/work/_actions/xxx/tizen-build-action/v1/build.sh: line 16: [public: command not found
```

fixes: #9

### CODE REVIEW

**Review by joeladam518 — APPROVED** [review]

**Review by Vacoris — APPROVED** [review]

**Review by wpankanin — APPROVED** [review]

File: build.sh [hunk 1]
```diff
@@ -13,7 +13,7 @@ PATH="$TIZEN_STUDIO/tools/ide/bin:$PATH"
 #
 # Parse arguments
 #
-if [$8 -eq 'partner']; then
+if [ "$8" = "partner" ]; then
     PRIVILEGE=parner
```
Comment (jyann) [inline build.sh:17]: why is there no "t" in this one?

Comment (iBotPeaches) [reply build.sh:17]: Tizen has a bug, so we present the proper spelling as an input to our action then pass the wrongly spelled, but right value onward to Tizen.

Comment (jyann) [reply build.sh:17]: oh that's fun

**Review by jyann — APPROVED** [review]
